version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.16.0-jessie
        environment:
          NODE_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: cj
      - image: postgres:11.3-alpine
        environment:
          POSTGRES_DB: airbnb_clone_listings
          POSTGRES_USER: cj
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm run seed
      - run: npm test